### ISSUE TITLE
Tried again to install NLTK on a Mac with python 3.6.0

### ISSUE THREAD

**Issue by danielrruf** [cltk/tutorials#10]
```
(venv) iMac-de-Daniel-2:cltk Daniel$ pip install cltk
Downloading/unpacking cltk
   Cannot fetch index base URL https://pypi.python.org/simple/
   Could not find any downloads that satisfy the requirement cltk
 Cleaning up...
 No distributions at all found for cltk
```
what I'm doing wrong?

**Comment by diyclassics** [comment]
Which version of pip is running in venv? Perhaps upgrade pip via ```pip install --upgrade pip```. I was able to install cltk just now using pip v. 10.0.1 (on OSX w. Python 3.6.5).

**Comment by danielrruf** [comment]
OK, `python3 -m pip install nltk` (instead of `pip install cltk`) did the trick, silly me. thanks for the info and the reassuring
