### ISSUE TITLE
Stuck again

### ISSUE THREAD

**Issue by danielrruf** [cltk/tutorials#11]
I was self deluded when I thought I had installed the cltk! I did create the directory, and I was able to create the virtual environment, in two ways: first using the directions given here (using the (apparently deprecated):
```
$ pyvenv venv
$ source venv/bin/activate
```
this way lead me nowhere where I could install cltk

I tried the "reccommended" way to create a virtual environment executing the command venv:

`python3 -m venv /path/to/new/virtual/environment`

OK, that creates 3 directories in the cltk (bin, include, lib) but, again, no way to install nltk. Whenever I try either

`python3 -m pip install cltk`

or

`pip install cltk`

I get the following (error messages ahead; please forgive the verbosity)

```
Collecting cltk
Requirement already satisfied: pyuca in ./anaconda3/lib/python3.6/site-packages (from cltk) (1.2)
Requirement already satisfied: pyyaml in ./anaconda3/lib/python3.6/site-packages (from cltk) (3.12)
Requirement already satisfied: gitpython in ./anaconda3/lib/python3.6/site-packages (from cltk) (2.1.10)
Collecting regex (from cltk)
Collecting python-crfsuite (from cltk)
  Using cached https://files.pythonhosted.org/packages/e7/e8/02618c1e926df4aee70308676511b728b1db4ca9eb52d8c4660c14a44178/python-crfsuite-0.9.5.tar.gz
Requirement already satisfied: whoosh in ./anaconda3/lib/python3.6/site-packages (from cltk) (2.7.4)
Requirement already satisfied: nltk in ./anaconda3/lib/python3.6/site-packages (from cltk) (3.2.5)
Requirement already satisfied: gitdb2>=2.0.0 in ./anaconda3/lib/python3.6/site-packages (from gitpython->cltk) (2.0.3)
Requirement already satisfied: six in ./anaconda3/lib/python3.6/site-packages (from nltk->cltk) (1.11.0)
Requirement already satisfied: smmap2>=2.0.0 in ./anaconda3/lib/python3.6/site-packages (from gitdb2>=2.0.0->gitpython->cltk) (2.0.3)
Building wheels for collected packages: python-crfsuite
  Running setup.py bdist_wheel for python-crfsuite ... error
  Complete output from command /Users/Daniel/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/yk/sfnlb4yx7sn_wj0jp99_q4y80000gn/T/pip-install-204cb9vp/python-crfsuite/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /private/var/folders/yk/sfnlb4yx7sn_wj0jp99_q4y80000gn/T/pip-wheel-s8h4n8tq --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.7-x86_64-3.6
  creating build/lib.macosx-10.7-x86_64-3.6/pycrfsuite
  copying pycrfsuite/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/pycrfsuite
  copying pycrfsuite/_dumpparser.py -> build/lib.macosx-10.7-x86_64-3.6/pycrfsuite
  copying pycrfsuite/_logparser.py -> build/lib.macosx-10.7-x86_64-3.6/pycrfsuite
  running build_ext
  building 'pycrfsuite._pycrfsuite' extension
  creating build/temp.macosx-10.7-x86_64-3.6
  creating build/temp.macosx-10.7-x86_64-3.6/pycrfsuite
  creating build/temp.macosx-10.7-x86_64-3.6/crfsuite
  creating build/temp.macosx-10.7-x86_64-3.6/crfsuite/lib
  creating build/temp.macosx-10.7-x86_64-3.6/crfsuite/lib/crf
  creating build/temp.macosx-10.7-x86_64-3.6/crfsuite/lib/crf/src
  creating build/temp.macosx-10.7-x86_64-3.6/crfsuite/swig
  creating build/temp.macosx-10.7-x86_64-3.6/crfsuite/lib/cqdb
  creating build/temp.macosx-10.7-x86_64-3.6/crfsuite/lib/cqdb/src
  creating build/temp.macosx-10.7-x86_64-3.6/liblbfgs
  creating build/temp.macosx-10.7-x86_64-3.6/liblbfgs/lib
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/Daniel/anaconda3/include -arch x86_64 -I/Users/Daniel/anaconda3/include -arch x86_64 -Icrfsuite/include/ -Icrfsuite/lib/cqdb/include -Iliblbfgs/include -Ipycrfsuite -I/Users/Daniel/anaconda3/include/python3.6m -c pycrfsuite/_pycrfsuite.cpp -o build/temp.macosx-10.7-x86_64-3.6/pycrfsuite/_pycrfsuite.o -std=c99
  error: invalid argument '-std=c99' not allowed with 'C++/ObjC++'
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for python-crfsuite
  Running setup.py clean for python-crfsuite
Failed to build python-crfsuite
Installing collected packages: regex, python-crfsuite, cltk
  Running setup.py install for python-crfsuite ... error
    Complete output from command /Users/Daniel/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/yk/sfnlb4yx7sn_wj0jp99_q4y80000gn/T/pip-install-204cb9vp/python-crfsuite/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/yk/sfnlb4yx7sn_wj0jp99_q4y80000gn/T/pip-record-x145uk_s/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.7-x86_64-3.6
    creating build/lib.macosx-10.7-x86_64-3.6/pycrfsuite
    copying pycrfsuite/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/pycrfsuite
    copying pycrfsuite/_dumpparser.py -> build/lib.macosx-10.7-x86_64-3.6/pycrfsuite
    copying pycrfsuite/_logparser.py -> build/lib.macosx-10.7-x86_64-3.6/pycrfsuite
    running build_ext
    building 'pycrfsuite._pycrfsuite' extension
    creating build/temp.macosx-10.7-x86_64-3.6
    creating build/temp.macosx-10.7-x86_64-3.6/pycrfsuite
    creating build/temp.macosx-10.7-x86_64-3.6/crfsuite
    creating build/temp.macosx-10.7-x86_64-3.6/crfsuite/lib
    creating build/temp.macosx-10.7-x86_64-3.6/crfsuite/lib/crf
    creating build/temp.macosx-10.7-x86_64-3.6/crfsuite/lib/crf/src
    creating build/temp.macosx-10.7-x86_64-3.6/crfsuite/swig
    creating build/temp.macosx-10.7-x86_64-3.6/crfsuite/lib/cqdb
    creating build/temp.macosx-10.7-x86_64-3.6/crfsuite/lib/cqdb/src
    creating build/temp.macosx-10.7-x86_64-3.6/liblbfgs
    creating build/temp.macosx-10.7-x86_64-3.6/liblbfgs/lib
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/Daniel/anaconda3/include -arch x86_64 -I/Users/Daniel/anaconda3/include -arch x86_64 -Icrfsuite/include/ -Icrfsuite/lib/cqdb/include -Iliblbfgs/include -Ipycrfsuite -I/Users/Daniel/anaconda3/include/python3.6m -c pycrfsuite/_pycrfsuite.cpp -o build/temp.macosx-10.7-x86_64-3.6/pycrfsuite/_pycrfsuite.o -std=c99
    error: invalid argument '-std=c99' not allowed with 'C++/ObjC++'
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/Users/Daniel/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/yk/sfnlb4yx7sn_wj0jp99_q4y80000gn/T/pip-install-204cb9vp/python-crfsuite/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/yk/sfnlb4yx7sn_wj0jp99_q4y80000gn/T/pip-record-x145uk_s/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/yk/sfnlb4yx7sn_wj0jp99_q4y80000gn/T/pip-install-204cb9vp/python-crfsuite/
```

**Comment by diyclassics** [comment]
@danielrruf Sorry to hear about continued difficulties here. As I mentioned in a previous reply, I use pipenv for this sort of thing and will be recommending that the CLTK Tutorial setup instruction do the same. I have drafted new instructions using pipenv on my fork of this repo: https://github.com/diyclassics/tutorials/blob/master/1%20CLTK%20Setup.ipynb

Perhaps you could try this method and see if you have more success this way. Let me know—PJB

**Comment by kylepjohnson** [comment]
Chiming in here, with a few comments:
* Our recommended way of installing: http://docs.cltk.org/en/latest/installation.html#with-pip
* I see from your output, I see that you are using an Anaconda-installed `/Users/Daniel/anaconda3/bin/python`. I have found it difficult to use Anaconda beside other versions of Python (`pipenv` as Patrick recommends may help, I don't know).
* Instead of the Anaconda environment, install the Mac OS X Python installer (<https://www.python.org/downloads/>). This should put a new Python executable at `/Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6`
* Now when making a virutalenv, use this one, like so:

``` shell
$ cd ~/Documents
$ python3.6 -m venv venv
$ source venv/bin/activate
$ pip install cltk
```

Now, each time you open a new terminal window, you must "activate" the environment again (`source ~/Documents/venv/bin/activate`).

I will close this issue, however please open it up if you want to talk more about this :)

**Comment by danielrruf** [comment]
Thanks Kyle,

This weekend I'll try again following your kind indications.

Best regards,

Daniel

2018-05-30 19:13 GMT+02:00 Kyle P. Johnson <notifications@github.com>:

**Comment by danielrruf** [comment]
Worked like a charm, thanks. Now, I was able to import all the Greek
corpora except TLG and PHI7. Whenevery I try to import them, I get the
following:

In [12]:  corpus_importer.import_corpus('tlg')
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-12-f759575fb80b> in <module>()
----> 1 corpus_importer.import_corpus('tlg')

~/venv/lib/python3.6/site-packages/cltk/corpus/utils/importer.py in
import_corpus(self, corpus_name, local_path, branch)
    361                 if corpus_name == 'tlg':
    362                     # normalize path for checking dir
--> 363                     if local_path.endswith('/'):
    364                         local_path = local_path[:-1]
    365                     # check for right corpus dir

AttributeError: 'NoneType' object has no attribute 'endswith'

2018-05-30 19:13 GMT+02:00 Kyle P. Johnson <notifications@github.com>:

**Comment by danielrruf** [comment]
oh! the local path! I fixed it and now it's OK with the TLG & PHI7. Thanks
and my apologies for the last (dumb) question!

2018-06-07 8:18 GMT+02:00 Daniel Riaño <danielrr2@gmail.com>:

**Comment by danielrruf** [comment]
Once again, a problem. I thought that providing a local path I could import
the TLG and PHI7 files. This is not the case. If I provide a local path as
a second argument, like this:

corpus_importer.import_corpus('tlg', '/Users/daniel/cltk_data/greek/')


CorpusImporter creates a folder called "originals" within "greek", and
inside it, it creates a folder called "tlg". So far so good. Only that
within the folder tag it creates an exact copy of the contents of
folder "/Users/daniel/cltk_data/greek"
"treebank" and "training set" included. Weird.

2018-06-07 13:22 GMT+02:00 Daniel Riaño <danielrr2@gmail.com>:

**Comment by kylepjohnson** [comment]
> This is not the case. If I provide a local path as a second argument, like this:

To import these into `~/cltk_data` you must already have the TLG or PHI corpora. Do you have them? We cannot distribute these.

**Comment by danielrruf** [comment]
All right now! Thanks. I missed the point. May I suggest that this piece of
info be included in the instructions for the installation? If I am right,
you (the user) provide a local path to a copy of the TLG files, and the
installer will make a copy of these files and put them inside a "tlg"
directory, itself placed inside an "originals" directory within the
cltk_data folder.

Thanks so much for the info!

I have been able to make the full installation on several machines, but I
can't pass the "install" step in *one* of them.

In this specific machine, I installed again Python3.6 after deleting all
Anaconda-related stuff, and started the cltk installation again. Whenever I
am inside the virtual environment and try (as per your instructions) to run
"pip install cltk", I get the following error:


Collecting cltk
...
(blah blah.. all righ until you reach this point:)

 Running setup.py install for nltk ... done
  Running setup.py install for python-crfsuite ... error
    Complete output from command /Users/Daniel/venv/bin/python3.6 -u -c
"import setuptools,
tokenize;__file__='/private/var/folders/yk/sfnlb4yx7sn_wj0jp99_q4y80000gn/T/pip-build-mvdtr0x7/python-crfsuite/setup.py';f=getattr(tokenize,
'open', open)(__file__);code=f.read().replace('\r\n',
'\n');f.close();exec(compile(code, __file__, 'exec'))" install --record
/var/folders/yk/sfnlb4yx7sn_wj0jp99_q4y80000gn/T/pip-srd10f1k-record/install-record.txt
--single-version-externally-managed --compile --install-headers
/Users/Daniel/venv/include/site/python3.6/python-crfsuite:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.6-intel-3.6
    creating build/lib.macosx-10.6-intel-3.6/pycrfsuite
    copying pycrfsuite/__init__.py ->
build/lib.macosx-10.6-intel-3.6/pycrfsuite
    copying pycrfsuite/_dumpparser.py ->
build/lib.macosx-10.6-intel-3.6/pycrfsuite
    copying pycrfsuite/_logparser.py ->
build/lib.macosx-10.6-intel-3.6/pycrfsuite
    running build_ext
    building 'pycrfsuite._pycrfsuite' extension
    creating build/temp.macosx-10.6-intel-3.6
    creating build/temp.macosx-10.6-intel-3.6/pycrfsuite
    creating build/temp.macosx-10.6-intel-3.6/crfsuite
    creating build/temp.macosx-10.6-intel-3.6/crfsuite/lib
    creating build/temp.macosx-10.6-intel-3.6/crfsuite/lib/crf
    creating build/temp.macosx-10.6-intel-3.6/crfsuite/lib/crf/src
    creating build/temp.macosx-10.6-intel-3.6/crfsuite/swig
    creating build/temp.macosx-10.6-intel-3.6/crfsuite/lib/cqdb
    creating build/temp.macosx-10.6-intel-3.6/crfsuite/lib/cqdb/src
    creating build/temp.macosx-10.6-intel-3.6/liblbfgs
    creating build/temp.macosx-10.6-intel-3.6/liblbfgs/lib
    gcc -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG
-g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g
-Icrfsuite/include/ -Icrfsuite/lib/cqdb/include -Iliblbfgs/include
-Ipycrfsuite -I/Users/Daniel/venv/include
-I/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c
pycrfsuite/_pycrfsuite.cpp -o
build/temp.macosx-10.6-intel-3.6/pycrfsuite/_pycrfsuite.o -std=c99
    error: invalid argument '-std=c99' not allowed with 'C++/ObjC++'
    error: command 'gcc' failed with exit status 1

    ----------------------------------------
Command "/Users/Daniel/venv/bin/python3.6 -u -c "import setuptools,
tokenize;__file__='/private/var/folders/yk/sfnlb4yx7sn_wj0jp99_q4y80000gn/T/pip-build-mvdtr0x7/python-crfsuite/setup.py';f=getattr(tokenize,
'open', open)(__file__);code=f.read().replace('\r\n',
'\n');f.close();exec(compile(code, __file__, 'exec'))" install --record
/var/folders/yk/sfnlb4yx7sn_wj0jp99_q4y80000gn/T/pip-srd10f1k-record/install-record.txt
--single-version-externally-managed --compile --install-headers
/Users/Daniel/venv/include/site/python3.6/python-crfsuite" failed with
error code 1 in
/private/var/folders/yk/sfnlb4yx7sn_wj0jp99_q4y80000gn/T/pip-build-mvdtr0x7/python-crfsuite/



Do you have any idea what this error message means?

2018-06-07 18:35 GMT+02:00 Kyle P. Johnson <notifications@github.com>:
