### ISSUE TITLE
How is this actually even used?

### ISSUE THREAD

**Issue by swasheck** [cltk/tutorials#12]
The tutorials do not really tell me how to use this. 

For example, what happens between #2 and #3?

So I can import corpora in step 2, and the dowload works because I can see them in ~/cltk_data/. Great. But now how do I use them? I don't really see a way to do this. Do I now have to read the files using `file.read()` or somesuch? Is the general goal to not use the corpora for analysis but to use them as trained data sets to analyze some other texts that we find?

**Comment by kylepjohnson** [comment]
> Do I now have to read the files using file.read() or somesuch?

Yes, exactly. For most text corpora, you need to write your own code to open these files.

The usual pattern to open a file:
``` python
with open (<filepath>) as file_open:
    text = file_open.read()
```

If you want to open multiple files in a directory, look at this: <https://stackoverflow.com/a/3207973>.

> Is the general goal to not use the corpora for analysis but to use them as trained data sets to analyze some other texts that we find?

Both, in fact! Some repos are simply for reading (<https://github.com/cltk/latin_text_latin_library>) while others just for training (<https://github.com/cltk/latin_training_set_sentence_cltk>). Others could be used for both, perhaps! (For example, using a treebank to either train a predictive model or to do statistics).

What is your goal in using the CLTK?

Closing but post back here with other questions.
