### ISSUE TITLE
Consider adding lex dispersion plot to tutorial notebook

### ISSUE THREAD

**Issue by kylepjohnson** [cltk/tutorials#16]
See code here: https://github.com/cltk/cltk/pull/537

**Comment by siddharthkv7** [comment]
Hello @kylepjohnson , can I get more info on the issue?
My doubt was that, lex dispersion plot is already a part of Tutorial 9 of cltk/tutorials (https://github.com/cltk/tutorials/blob/master/9%20Lexical%20Dispersion%20Plot.ipynb)
Is this the same thing as you were hoping to implement?

**Comment by kylepjohnson** [comment]
@siddharthkv7  you're right. Thank you for offering and THANK YOU for noticing that this was already done. It was added last summer, but somehow the old PR was never closed (I blame myself  :disappointed:).

If you do want a fairly easy project, you could make make a directory and a few notebooks for all of our South Asian languages (Begali, Gujarati, etc.). Does this interest you?

**Comment by siddharthkv7** [comment]
@kylepjohnson Yes, I am very much interested in this project !
I am a beginner to open source, but I would be extremely happy to help. I was hoping if you could provide me with further inputs regarding the same.

**Comment by kylepjohnson** [comment]
Sure. Have you used Jupyter notebooks before? If not, learn how to use these, and then pull these notebooks and try adding some new ones with examples from our docs.

This enough to get you started?

**Comment by siddharthkv7** [comment]
Thanks a lot, @kylepjohnson!  Yes, I guess I shall be able to get myself started. :D
If I am not wrong, I can probably use this [Old Norse Tutorial](https://github.com/cltk/tutorials/blob/bac40101e4caef5281a7ee9ada334ff0b7636682/languages/old-norse/old-norse-tutorial.ipynb) which was a result of [13](https://github.com/cltk/tutorials/pull/13) as a reference for format maybe?

**Comment by clemsciences** [comment]
Hey @siddharthkv, the Old Norse tutorial may be used as a model, even if it is not perfect. I think I'm going to update soon this notebook because more functions for Old Norse have been added since the last update.
