### ISSUE TITLE
Possible edit in Tutorial 9 notebook - importing of indian_punctuation_tokenize_regex

### ISSUE THREAD

**Issue by siddharthkv7** [cltk/tutorials#17]
In the [Tutorial 9](https://github.com/cltk/tutorials/blob/master/9%20Lexical%20Dispersion%20Plot.ipynb), importing of `indian_tokenizer `might fail. This is probably because `indian_tokenizer` is now a part of `sentence.py` as a result of [702](https://github.com/cltk/cltk/pull/702) and `indian_punctuation_tokenize_regex()` is now a part of class `TokenizeSentence()` 
Although there is no example of this function being used in this Tutorial notebook, the error due to import can be avoided.

**Comment by kylepjohnson** [comment]
Good observation. Please run the notebook and see if it errors. Either the docs or this notebook is out of date (probably the notebook). I'll wait for your fix :)
