### ISSUE TITLE
Nothing here ?

### ISSUE THREAD

**Issue by clemsciences** [cltk/tutorials#2]
Hey contributors, why is there nothing here ? When I find time, I'll write a tutorial to use tools for Old Norse (the ones I programmed). It will help beginners .

**Comment by kylepjohnson** [comment]
👍 I agree! These tutorials should be as important as the docs.

By the way, here is a great new site that I found last night: https://hub.mybinder.org/user/cltk-tutorials-tn9ln0ko/tree

It lets you interact with notebooks, which can be even more helpful in helping students learn how to use our code.

**Comment by clemsciences** [comment]
I get a 403 error which means I'm not allowed to reach this web site. I think I'm going firstly to make a simple tutorial then, why not, make an interactive tutorial, so that, to begin with, I think and elaborate the core tutorial.

**Comment by kylepjohnson** [comment]
Huh. They must spin down a notebook if someone stops using it.
-- 
Kyle P. Johnson, Ph.D.

Natural language processing, AI
https://kyle-p-johnson.com | http://cltk.org

**Comment by clemsciences** [comment]
Hey there,

I'm still thinking about the best form for a new tutorial. Your tutorial and the future one must be complementary. Should it be like a challenge or like an easy stuff just to see more elaborate uses of code  than in the docs? That's not as easy as I imagined...

I found out Jupyter can be used with Nbgrader so that questions can be asked and answers can be analysed and a mark is given. I'm not sure if it can be useful to beginners.

**Comment by kylepjohnson** [comment]
Hi @clemsciences Instead of over-thinking the ideal new tutorials organization, how about you simply share you Old Norse notebooks in one file, just called `Old Norse.ipynb`? Or if more than one is necessary, `Old Norse 1.ipynb`, `Old Norse 2.ipynb`, `...`.

**Comment by clemsciences** [comment]
Hey @kylepjohnson, I wrote a quite precise (but still not enough and not finished) tutorial to use and process the Old Norse corpora : https://github.com/clemsciences/old_norse_notebook a pull request is going to come soon.

**Comment by diyclassics** [comment]
@kylepjohnson re: Binder—use this address for the public-facing notebooks: https://mybinder.org/v2/gh/cltk/tutorials.git/master

**Comment by diyclassics** [comment]
It would be nice to have this repo organized so that individual languages are on separate forks with the same nine-part set of notebooks, i.e. notebook 3 would be 'Basic NLP' on every fork (ideally with the same or—similar, as appropriate—workflow), but it would have language-specific code.
