### ISSUE TITLE
Issue in 3. Basic NLP.ipynb tokenize_sentence() example.

### ISSUE THREAD

**Issue by Pancham97** [cltk/tutorials#8]
`tokenizer = TokenizeSentence('latin')` shows an error because the `cltk.tokenize.sentence` only accepts Indian Languages.
Fix the language barrier in the `sentence.py` constructor.

**Comment by diyclassics** [comment]
I was unable to reproduce this error on a fresh install of the CLTK (both installing from pypi and from git with the current master) and the Latin models. Can you try again? If you are still getting the error, can you give the full traceback, and any other details that you think would help. Thanks, PJB

**Comment by stellargo** [comment]
Yeah I even i cant reproduce this errror.
