### ISSUE TITLE
pyvenv

### ISSUE THREAD

**Issue by danielrruf** [cltk/tutorials#9]
If you try to instal pyenv, as per your instructions

pyvenv venv

the terminal will reply:

WARNING: the pyenv script is deprecated in favour of `python3.6 -m venv`

so, what's one to do next) :)

**Comment by diyclassics** [comment]
Even though it is deprecated, it should still work for now. Do you have a folder called 'venv' inside the 'cltk' folder? Does ```source venv/bin/activate``` work? If so, you should be able to proceed with the rest of the tutorial?

**Comment by diyclassics** [comment]
That said... I would be in favor of updating our installation guidelines to use [pipenv](https://github.com/pypa/pipenv). @kylepjohnson, thoughts?

**Comment by danielrruf** [comment]
2018-05-02 15:25 GMT+02:00 Patrick J. Burns <notifications@github.com>:

> Even though it is deprecated, it should still work for now. Do you have a
> folder called 'venv' inside the 'cltk' folder?
>
yes



> Does source venv/bin/activate?
>

yes, it makes the venv enrironment to open in the terminal (I am
completely  unfamiliar with this environment)

> If so, you should be able to proceed with the rest of the tutorial?
>

actually not. I go to the Terminal, open a Jupyter notebook from within
~/cltk ; then go to http://localhost:8888 in firefox. There i choose New
(Notebook): Python 3 ; the notebook appears (a box) and I type


from cltk.corpus.utils.importer import CorpusImporter

Only to receive the following message:

---------------------------------------------------------------------------ModuleNotFoundError
                      Traceback (most recent call
last)<ipython-input-4-4a045e3d9483> in <module>()----> 1 from
cltk.corpus.utils.importer import CorpusImporter
ModuleNotFoundError: No module named 'cltk'



An I'm stuck there! I think I am in the right directory since the first
line to appear in the terminal after I type "jupyter notebook" is

Serving notebooks from local directory: /Users/daniestudio/cltk
>




thanks for the help,

Daniel

**Comment by diyclassics** [comment]
Have you installed cltk, i.e. ```pip install cltk``` after activating venv? You will know that the venv is activated because '(venv)' will appear at the left side of your command line prompt.

**Comment by danielrruf** [comment]
Yes, I did, and [venv] appears as you mentioned

2018-05-02 19:11 GMT+02:00 Patrick J. Burns <notifications@github.com>:
